### basic settings

# site properties and page defaults
title: Zelezniak Lab
description: blablabll
logo: images/logo.svg
header: images/background.jpg
footer: images/background.jpg
baseurl: ""

# site social media and other links
links:
  email: aleksej.zelezniak@chalmers.se
  google-scholar: Aleksej Zelezniak
  github: https://github.com/zelezniak-lab/
  twitter: azelezniak
  instagram: ""
  youtube: ""

### advanced settings

# automatic citations
auto-cite:
  plugins:
    - name: sources
      input:
        - ../_data/sources.yaml
  output: ../_data/citations.yaml

# default front matter parameters for markdown files
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

# collections
collections:
  members:
    output: true

# sass settings
sass:
  sass_dir: css

# syntax highlighting
highlighter: rouge

# plugins
plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
  # - jekyll-github-metadata
  # - jekyll-avatar
  # - jekyll-gist
  # - jekyll-mentions
  # - jekyll-relative-links
  # - jemoji

# jekyll theme
theme: null
